<?php

use Illuminate\Database\Seeder;
use App\Models\Floorreport;

class FloorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       $floorreport = [
        	[
                'id' => '1',
                'room' => '101',
                'code' => 'OD',
                'name' => 'Sueb',
                'person' => '2',
                'remark' => '',
            ],
            [
                'id' => '2',
                'room' => '102',
                'code' => 'VR',
                'name' => '-',
                'person' => '0',
                'remark' => '-',
            ],     
            [
                'id' => '3',
                'room' => '103',
                'code' => 'OO',
                'name' => '-',
                'person' => '0',
                'remark' => 'Masih di perbaiki',
            ],
            [
                'id' => '4',
                'room' => '104',
                'code' => 'VR',
                'name' => '-',
                'person' => '0',
                'remark' => '-',
            ],     
            [
                'id' => '5',
                'room' => '105',
                'code' => 'VR',
                'name' => '-',
                'person' => '0',
                'remark' => '',
            ],
            [
                'id' => '6',
                'room' => '106',
                'code' => 'VR',
                'name' => '-',
                'person' => '0',
                'remark' => '-',
            ],     
            [
                'id' => '7',
                'room' => '107',
                'code' => 'VR',
                'name' => '-',
                'person' => '0',
                'remark' => '-',
            ],
            [
                'id' => '8',
                'room' => '108',
                'code' => 'VR',
                'name' => '-',
                'person' => '0',
                'remark' => '-',
            ],     
            [
                'id' => '9',
                'room' => '109',
                'code' => 'VR',
                'name' => '-',
                'person' => '0',
                'remark' => '-',
            ],
            [
                'id' => '10',
                'room' => '110',
                'code' => 'VR',
                'name' => '-',
                'person' => '0',
                'remark' => '-',
            ],     
            [
                'id' => '11',
                'room' => '111',
                'code' => 'VR',
                'name' => '-',
                'person' => '0',
                'remark' => '-',
            ],
            [
                'id' => '12',
                'room' => '112',
                'code' => 'VR',
                'name' => '-',
                'person' => '0',
                'remark' => '-',
            ],
            //200
            [
                'id' => '13',
                'room' => '201',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],
            [
                'id' => '14',
                'room' => '202',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],                  
            [
                'id' => '15',
                'room' => '203',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],
            [
                'id' => '16',
                'room' => '204',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],                  
            [
                'id' => '17',
                'room' => '205',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],
            [
                'id' => '18',
                'room' => '206',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],                  
            [
                'id' => '19',
                'room' => '207',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],
            [
                'id' => '20',
                'room' => '208',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],                  
            [
                'id' => '21',
                'room' => '209',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],
            [
                'id' => '22',
                'room' => '210',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],                  
            [
                'id' => '23',
                'room' => '211',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],
            [          
                'id' => '24',
                'room' => '212',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],          
            //300
            [
                'id' => '25',
                'room' => '301',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],
            [
                'id' => '26',
                'room' => '302',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],                  
            [
                'id' => '27',
                'room' => '303',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],
            [
                'id' => '28',
                'room' => '304',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],                  
            [
                'id' => '29',
                'room' => '305',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],
            [
                'id' => '30',
                'room' => '306',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],                  
            [
                'id' => '31',
                'room' => '307',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],
            [
                'id' => '32',
                'room' => '308',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],                  
            [
                'id' => '33',
                'room' => '309',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],
            [
                'id' => '34',
                'room' => '310',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],                  
            [
                'id' => '35',
                'room' => '311',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ],
            [          
                'id' => '36',
                'room' => '312',
                'code' => 'VR',
                'person' => '0',
                'name' => '',
                'remark' => '',
            ]          
        ];
        Floorreport::insert($floorreport);
    }
}
